# Generated by Django 5.2.4 on 2025-07-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipping',
            name='shipping_duration',
            field=models.CharField(default='standard', max_length=50),
        ),
        migrations.AddField(
            model_name='shipping',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
