# Generated by Django 5.2.4 on 2025-07-26 20:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('orders', '0002_shipping_shipped_shipping_shipping_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='shipped',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='coupons.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='shipping_duration',
            field=models.CharField(choices=[('standard', 'Standard'), ('express', 'Express')], default='standard', max_length=10),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
