# Generated by Django 5.2.4 on 2025-07-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='tax',
        ),
    ]
